version: "3"
services:
  mymongodb:
    image: mongo:latest
    container_name: mymongodb
    ports:
      - 27017:27017
  mediscreen-note:
    image: mediscreen/note-image
    container_name: mediscreen-note-container-1
    ports:
      - 9102:9102
    links:
      - mymongodb
